FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -yq --no-install-recommends \
            python3 python3-pip lsb-release sudo git

RUN git clone https://github.com/Dasharo/fwupd.git && \
    ./fwupd/contrib/ci/fwupd_setup_helpers.py install-dependencies --yes -o ubuntu && \
    rm -rf fwupd
