FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -yq --no-install-recommends \
            python3 python3-pip lsb-release sudo

COPY ./contrib /contrib

RUN /contrib/ci/fwupd_setup_helpers.py install-dependencies --yes -o ubuntu
