name: Continuous Integration
on:
  push:
    branches: [ dasharo-release ]
  pull_request:
    branches:
      - dasharo-develop
      - dasharo-release

jobs:
  build:
    runs-on: [self-hosted, builder]
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Build in container
        env:
          CI_NETWORK: true
          CI: true
        run: |
          echo $GITHUB_WORKSPACE
          docker run --privileged -e CI=true -t -v $GITHUB_WORKSPACE:/github/workspace docker.pkg.github.com/dasharo/fwupd/fwupd-${{matrix.os}}:latest

      - name: Save build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dasharo-fwupd
          path: |
            dist/
          retention-days: 7

