name: Continuous Integration
on:
  push:
    branches: [ ci-verify2 ]
  pull_request:
    branches:
      - dasharo-develop
      - dasharo-release

jobs:
  build:
    runs-on: [self-hosted, builder]
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Build in container
        env:
          CI_NETWORK: true
          CI: true
        run: |
          echo $GITHUB_WORKSPACE
          mkdir tss
          docker run -e CI=false -t -v tss:/usr/include/tss -v $GITHUB_WORKSPACE:/github/workspace docker.pkg.github.com/dasharo/fwupd/fwupd-${{matrix.os}}:latest

      - name: Save build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dasharo-fwupd
          path: |
            dist/
          retention-days: 7

      - name: Get Actions user id
        id: get_uid
        run: |
          actions_user_id=`id -u $USER`
          echo $actions_user_id
          echo ::set-output name=uid::$actions_user_id

      - name: Correct Ownership in GITHUB_WORKSPACE directory
        uses: peter-murray/reset-workspace-ownership-action@v1
        with:
          user_id: ${{ steps.get_uid.outputs.uid }}
